### ISSUE TITLE
SQL vulnerability

### ISSUE THREAD

**Issue by MathiasChaouche** [Goatella/Simple-PHP-Login#5]
The file login.php is vulnerable to two SQL injections:
if the user submits the login a' OR '1'='1' LIMIT 1,2# , he is able to connect as any user who uses a given password
if the user submits admin' AND password LIKE '0% , he is able based on the response to determine whether or not the admin password hash begins with 0, and eventually get the whole hash.

**Comment by dirobu** [comment]
get my repository (uprootPHP) it will filter xss and injection automatically.
